version: '3.5'
 
services:
  mongodb:
    container_name: sample_database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks: 
      - systemnetwork

  redis:
    container_name: sample_cache
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - systemnetwork

  backend:
    container_name: sample_backend
    build: .
    env_file: 
      - .env
    volumes: 
      - .:/usr/src/app/
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb
      - redis
    networks: 
      - systemnetwork
      - samplenetwork
    restart: on-failure

  # frontend:
  #   container_name: sample_frontend
  #   build: ./web
  #   ports: 
  #     - "80:80"
  #   depends_on: 
  #     - backend
  #   networks: 
  #     - samplenetwork
  # nginx:
  #   build: "./nginx"
  #   restart: always
  #   expose:
  #     - "80"
  #   ports:
  #     - "5055:80"
  #     - "443:443"
  #   depends_on: 
  #     - golang
  #   networks: 
  #     - marketnetwork
      
networks:
  systemnetwork:
    driver: bridge
  samplenetwork:
 
volumes:
    mongodb_data_container: