package handlers

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/omekov/sample/config"
	_ "github.com/omekov/sample/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/omekov/sample/internal/apiserver/stores"

	"github.com/gorilla/mux"
	"github.com/sirupsen/logrus"
	httpSwagger "github.com/swaggo/http-swagger"
)

// Server ...
type Server struct {
	Config *Config
	Logger *logrus.Logger
	Store  *stores.Store
}

// Config ...
type Config struct {
	Router *mux.Router
	http.Server
	ShutdownReq chan bool
	ReqCount    uint32
}

func (c *Config) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	c.Router.ServeHTTP(w, r)
}

// ConfigureRouter ...
func ConfigureRouter() *Config {
	return &Config{
		Router: mux.NewRouter(),
		Server: http.Server{
			Addr:         ":" + config.IsReadyENV(config.PORT),
			ReadTimeout:  10 * time.Second,
			WriteTimeout: 10 * time.Second,
		},
		ShutdownReq: make(chan bool),
	}
}

// Handlers ...
func (s *Server) handlers() *mux.Router {
	s.Config.Router.Use(s.setRequestID)
	s.Config.Router.Use(s.setHeader)
	s.Config.Router.Use(mux.CORSMethodMiddleware(s.Config.Router))
	s.Config.Router.Use(s.logRequest)
	s.Config.Router.HandleFunc("/signin", s.signIn()).Methods(http.MethodPost, http.MethodOptions)
	s.Config.Router.HandleFunc("/signup", s.signUp()).Methods(http.MethodPost, http.MethodOptions)
	s.Config.Router.HandleFunc("/refresh", s.refreshToken()).Methods(http.MethodPost, http.MethodOptions)
	s.Config.Router.HandleFunc("/shutdown", s.shutdown()).Methods(http.MethodGet, http.MethodOptions)
	private := s.Config.Router.PathPrefix("/api").Subrouter()
	private.Use(s.authenticateUser)
	private.HandleFunc("/whoami", s.whoami()).Methods(http.MethodGet, http.MethodOptions)

	// Swagger
	s.Config.Router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	return s.Config.Router
}

func (s *Server) waitShutdown() {
	signalChan := make(chan os.Signal, 1)
	signal.Notify(
		signalChan,
		syscall.SIGHUP,  // kill -SIGHUP XXXX
		syscall.SIGINT,  // kill -SIGINT XXXX or Ctrl+c
		syscall.SIGQUIT, // kill -SIGQUIT XXXX
	)

	select {
	case sig := <-signalChan:
		log.Printf("Shutdown request (signal: %v)", sig)
	case sig := <-s.Config.ShutdownReq:
		log.Printf("Shutdown request (/shutdown %v)", sig)
	}

	log.Printf("Stoping http server ...")
	//Create shutdown context with 10 second timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	//shutdown the server
	if err := s.Config.Shutdown(ctx); err != nil {
		log.Printf("shutdown error: %v\n", err)
		defer os.Exit(1)
		return
	} else {
		log.Printf("gracefully stopped\n")
	}
	cancel()

	defer os.Exit(0)
	return
}

// Run ...
func (s *Server) Run() {
	server := ConfigureRouter()
	server.Handler = s.handlers()
	done := make(chan bool)
	go func() {
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Failed to initialize server: %v\n", err)
		}
		done <- true
	}()

	//wait shutdown
	s.waitShutdown()

	<-done
}
