basePath: /
definitions:
  http.Credential:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  http.Error:
    properties:
      error:
        type: string
    type: object
  http.Token:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
host: localhost
info:
  contact:
    name: API Support
  description: This is a sample service for managment
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Sample API
  version: "2.0"
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: Sign auth client the input paylod
      parameters:
      - description: SignIn auth
        in: body
        name: signin
        required: true
        schema:
          $ref: '#/definitions/http.Credential'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.Error'
      summary: Sign auth
      tags:
      - sign
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
