definitions:
  models.Customer:
    properties:
      firstname:
        example: Adam
        type: string
      password:
        example: "123456"
        type: string
      registrationDate:
        example: "2020-09-09T21:21:46+00:00"
        type: string
      releaseDate:
        example: "2020-09-09T22:21:46+00:00"
        type: string
      username:
        example: example@gmail.com
        type: string
    type: object
  models.Podcast:
    properties:
      author:
        example: example@gmail.com
        type: string
      title:
        example: title
        type: string
    type: object
  models.SignInput:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: example@gmail.com
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /podcasts:
    get:
      consumes:
      - application/json
      description: Get details of all podcasts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Podcast'
            type: array
      summary: Get details of all podcasts
      tags:
      - podcasts
    post:
      consumes:
      - application/json
      description: Create a new podcast with the input paylod
      parameters:
      - description: Create podcast
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Podcast'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Podcast'
      summary: Create a new podcast
      tags:
      - podcasts
  /profile:
    post:
      consumes:
      - application/json
      description: Profile customer the input paylod
      parameters:
      - description: Profile customer
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/models.Customer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Customer'
      summary: Profile customer
      tags:
      - sign
  /signin:
    post:
      consumes:
      - application/json
      description: Sign auth client the input paylod
      parameters:
      - description: SignIn auth
        in: body
        name: signin
        required: true
        schema:
          $ref: '#/definitions/models.SignInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SignInput'
      summary: Sign auth
      tags:
      - sign
  /signup:
    post:
      consumes:
      - application/json
      description: Sign Up new customer the input paylod
      parameters:
      - description: SignUp customer
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/models.Customer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Customer'
      summary: Sign Up new customer
      tags:
      - sign
swagger: "2.0"
